apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: easyinsights
resources: [../../base]
images:
  - name: easyinsights-web
    newName: ghcr.io/ooarchitect92/easyinsights-web
    newTag: 1.0.0
  - name: easyinsights-worker
    newName: ghcr.io/ooarchitect92/easyinsights-worker
    newTag: 1.0.0
  - name: easyinsights-tooling
    newName: ghcr.io/ooarchitect92/easyinsights-tooling
    newTag: 1.0.0
patches:
  - path: production-config.yaml
  - path: production-replicas.yaml
