apiVersion: apps/v1
kind: Deployment
metadata:
  name: easyinsights-web
  namespace: easyinsights
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: easyinsights-outbox
  namespace: easyinsights
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: easyinsights-consumer
  namespace: easyinsights
spec:
  replicas: 4
